-- Seed data for Diamante Azul - Produtos de Metais Sanitários
-- Categorias
INSERT INTO categories (nome, slug, descricao, imagem_url, ativo, ordem) VALUES
('Cozinha', 'cozinha', 'Torneiras e cubas para cozinha', 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=400', true, 1),
('Banheiro', 'banheiro', 'Torneiras, duchas e acessórios para banheiro', 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=400', true, 2),
('Kits', 'kits', 'Kits completos com torneira e cuba', 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400', true, 3),
('Área Externa', 'area-externa', 'Torneiras para jardim e áreas externas', 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400', true, 4),
('Acessórios', 'acessorios', 'Válvulas, sifões, flexíveis e mais', 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=400', true, 5),
('Ofertas', 'ofertas', 'Produtos em promoção', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400', true, 6);

-- Produtos
INSERT INTO products (
  category_id, nome, slug, descricao_curta, descricao_completa, 
  preco, preco_promocional, sku, estoque, peso_kg, altura_cm, largura_cm, comprimento_cm,
  ativo, destaque, imagens, especificacoes, tags
) VALUES
-- Produtos Cozinha
((SELECT id FROM categories WHERE slug = 'cozinha'), 'Torneira Monocomando Gourmet Extensível', 'torneira-monocomando-gourmet-extensivel', 'Torneira gourmet com mangueira extensível', 'Torneira monocomando gourmet com mangueira extensível de 60cm. Acabamento em aço inox escovado. Ideal para cozinhas modernas.', 599.90, 299.90, 'TOR-GOUR-001', 50, 1.5, 35, 8, 25, true, true, '[{"url":"https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800","principal":true},{"url":"https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800","principal":false}]', '{"Material": "Aço Inox 304", "Acabamento": "Escovado", "Pressão": "0.5 a 6 bar", "Garantia": "5 anos"}', '{"destaque","gourmet","cozinha"}'),

((SELECT id FROM categories WHERE slug = 'cozinha'), 'Torneira Elétrica Purificadora', 'torneira-eletrica-purificadora', 'Torneira elétrica com filtro integrado', 'Torneira elétrica purificadora com sistema de filtragem de 3 estágios. Água quente e gelada instantânea. Design moderno.', 899.90, 699.90, 'TOR-ELET-002', 30, 2.0, 40, 10, 20, true, true, '[{"url":"https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800","principal":true}]', '{"Potência": "1500W", "Capacidade": "2L/min", "Filtro": "3 estágios", "Cor": "Cromado"}', '{"eletrica","purificador","lancamento"}'),

((SELECT id FROM categories WHERE slug = 'cozinha'), 'Cuba de Inox 304 60x45', 'cuba-inox-304-60x45', 'Cuba de inox escovado 60x45cm', 'Cuba de aço inox 304 de alta qualidade. Acabamento escovado, válvula de 4.5 polegadas inclusa. Profundidade de 20cm.', 459.90, 349.90, 'CUB-6045-003', 40, 3.5, 20, 45, 60, true, false, '[{"url":"https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800","principal":true}]', '{"Material": "Aço Inox 304", "Dimensões": "60x45x20cm", "Válvula": "4.5\" inclusa", "Acabamento": "Escovado"}', '{"cuba","inox","cozinha"}'),

((SELECT id FROM categories WHERE slug = 'cozinha'), 'Torneira Gourmet Monocomando Black', 'torneira-gourmet-monocomando-black', 'Torneira gourmet preta fosca', 'Torneira gourmet monocomando com design moderno na cor preta fosca. Bica alta 360° giratória. Ideal para cozinhas contemporâneas.', 529.90, 389.90, 'TOR-BLK-004', 35, 1.8, 38, 9, 22, true, true, '[{"url":"https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800","principal":true}]', '{"Material": "Latão cromado", "Acabamento": "Preta fosca", "Rotação": "360°", "Instalação": "Monocomando"}', '{"black","gourmet","moderno"}'),

-- Produtos Banheiro
((SELECT id FROM categories WHERE slug = 'banheiro'), 'Ducha Higiênica Monocomando', 'ducha-higienica-monocomando', 'Ducha higiênica com monocomando', 'Ducha higiênica monocomando de metal cromado. Acionamento suave e preciso. Mangueira de 1.20m inclusa.', 189.90, 129.90, 'DUCH-HIG-005', 60, 0.8, 15, 8, 12, true, true, '[{"url":"https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800","principal":true}]', '{"Material": "Latão cromado", "Mangueira": "1.20m metal", "Pressão": "0.5 a 5 bar", "Garantia": "3 anos"}', '{"higiene","banheiro","monocomando"}'),

((SELECT id FROM categories WHERE slug = 'banheiro'), 'Torneira Cascata Alta Black', 'torneira-cascata-alta-black', 'Torneira cascata alta preta fosca', 'Torneira de bancada estilo cascata na cor preta fosca. Design moderno e sofisticado. Ideal para banheiros contemporâneos.', 449.90, 329.90, 'TOR-CAS-006', 25, 1.6, 30, 12, 18, true, true, '[{"url":"https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800","principal":true}]', '{"Material": "Latão cromado", "Acabamento": "Preta fosca", "Tipo": "Cascata", "Altura": "30cm"}', '{"cascata","black","luxo"}'),

((SELECT id FROM categories WHERE slug = 'banheiro'), 'Ducha Chuveiro Elétrico 5500W', 'ducha-chuveiro-eletrico-5500w', 'Chuveiro elétrico 5500W 4 temperaturas', 'Chuveiro elétrico de alta potência com 4 opções de temperatura. Resistência blindada anti-furto. Design moderno.', 159.90, 99.90, 'DUCH-5500-007', 80, 1.2, 25, 15, 20, true, false, '[{"url":"https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800","principal":true}]', '{"Potência": "5500W", "Voltagem": "220V", "Temperaturas": "4 níveis", "Resistência": "Blindada"}', '{"eletrico","ducha","promocao"}'),

((SELECT id FROM categories WHERE slug = 'banheiro'), 'Cuba de Apoio Cerâmica Branca', 'cuba-apoio-ceramica-branca', 'Cuba de apoio em cerâmica branca', 'Cuba de apoio em cerâmica de alta qualidade na cor branca. Acabamento brilhante e fácil limpeza. Tamanho 40x40cm.', 299.90, 229.90, 'CUB-APO-008', 30, 4.0, 15, 40, 40, true, true, '[{"url":"https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800","principal":true}]', '{"Material": "Cerâmica", "Cor": "Branco brilhante", "Dimensões": "40x40x15cm", "Instalação": "Sobrepor"}', '{"cuba","ceramica","banheiro"}'),

-- Produtos Kits
((SELECT id FROM categories WHERE slug = 'kits'), 'Kit Cuba Inox + Torneira Gourmet', 'kit-cuba-inox-torneira-gourmet', 'Kit completo cuba e torneira', 'Kit completo com cuba de inox 50x40cm e torneira gourmet monocomando. Válvula e sifão inclusos. Promoção especial!', 699.90, 499.90, 'KIT-CUB-009', 20, 4.5, 20, 40, 50, true, true, '[{"url":"https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800","principal":true}]', '{"Cuba": "Inox 50x40cm", "Torneira": "Monocomando", "Inclusos": "Válvula + Sifão", "Desconto": "29% OFF"}', '{"kit","promocao","completo"}'),

((SELECT id FROM categories WHERE slug = 'kits'), 'Kit Banheiro Completo 5 Peças', 'kit-banheiro-completo-5-pecas', 'Kit com 5 peças para banheiro', 'Kit completo para banheiro com 5 peças: torneira lavatório, ducha higiênica, acabamentos e válvula. Acabamento cromado.', 399.90, 289.90, 'KIT-BAN-010', 25, 3.0, 30, 25, 35, true, true, '[{"url":"https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800","principal":true}]', '{"Peças": "5 itens", "Material": "Latão cromado", "Garantia": "5 anos", "Instalação": "Completa"}', '{"kit","banheiro","completo"}'),

-- Produtos Área Externa
((SELECT id FROM categories WHERE slug = 'area-externa'), 'Torneira Jardim Metal 1/2', 'torneira-jardim-metal-12', 'Torneira para jardim 1/2 metal', 'Torneira de metal cromado para áreas externas. Rosca 1/2 polegada. Resistente às intempéries.', 49.90, 29.90, 'TOR-JAR-011', 100, 0.4, 12, 6, 8, true, false, '[{"url":"https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800","principal":true}]', '{"Material": "Metal cromado", "Rosca": "1/2\"", "Uso": "Externo", "Resistência": "Intempéries"}', '{"jardim","externo","resistente"}'),

((SELECT id FROM categories WHERE slug = 'area-externa'), 'Torneira Tanque Dupla Saída', 'torneira-tanque-dupla-saida', 'Torneira dupla saída para tanque', 'Torneira para tanque com dupla saída. Uma para máquina de lavar e outra para uso geral. Metal resistente.', 89.90, 59.90, 'TOR-TAN-012', 45, 0.6, 18, 8, 15, true, true, '[{"url":"https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800","principal":true}]', '{"Material": "Latão cromado", "Saídas": "Dupla", "Uso": "Tanque/Lavar", "Acabamento": "Cromado"}', '{"tanque","dupla","utilitario"}'),

-- Produtos Acessórios
((SELECT id FROM categories WHERE slug = 'acessorios'), 'Sifão Copo Cromado 1.1/2', 'sifao-copo-cromado-112', 'Sifão copo cromado 1.1/2 polegada', 'Sifão copo cromado de alta qualidade. Rosca 1.1/2 polegada. Com escape de ar. Material resistente.', 39.90, 24.90, 'SIF-COP-013', 150, 0.3, 20, 8, 10, true, false, '[{"url":"https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800","principal":true}]', '{"Material": "ABS cromado", "Rosca": "1.1/2\"", "Com escape": "Sim", "Uso": "Cozinha/Banheiro"}', '{"sifao","cromado","acessorio"}'),

((SELECT id FROM categories WHERE slug = 'acessorios'), 'Válvula de Escoamento 4.1/2', 'valvula-escoamento-412', 'Válvula de escoamento 4.1/2 cromada', 'Válvula de escoamento cromada 4.1/2 polegadas. Com tampa de metal. Encaixe universal.', 69.90, 44.90, 'VAL-ESC-014', 80, 0.5, 15, 10, 10, true, true, '[{"url":"https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800","principal":true}]', '{"Material": "Latão cromado", "Tamanho": "4.1/2\"", "Tampa": "Metal", "Tipo": "Click"}', '{"valvula","escoamento","click"}'),

((SELECT id FROM categories WHERE slug = 'acessorios'), 'Flexível 60cm Inox Malha', 'flexivel-60cm-inox-malha', 'Flexível 60cm malha de inox', 'Flexível de 60cm com malha de aço inox. Conexões 1/2 polegada. Resistente à pressão e corrosão.', 29.90, 19.90, 'FLEX-60-015', 200, 0.2, 60, 2, 2, true, false, '[{"url":"https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800","principal":true}]', '{"Comprimento": "60cm", "Material": "Malha inox", "Conexões": "1/2\"", "Pressão": "Até 10 bar"}', '{"flexivel","inox","conexao"}'),

-- Produtos Ofertas (promoções)
((SELECT id FROM categories WHERE slug = 'ofertas'), 'Torneira Cozinha Bica Móvel - PROMOÇÃO', 'torneira-cozinha-bica-movel-promocao', 'Torneira bica móvel promoção', 'Torneira de cozinha bica móvel tradicional. Acabamento cromado. Modelo básico e funcional. Super promoção!', 89.90, 49.90, 'PROMO-016', 50, 0.9, 22, 7, 12, true, true, '[{"url":"https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800","principal":true}]', '{"Material": "Latão cromado", "Modelo": "Bica móvel", "Economia": "45% OFF", "Garantia": "1 ano"}', '{"promocao","basico","economico"}'),

((SELECT id FROM categories WHERE slug = 'ofertas'), 'Ducha Higiênica Plástica - LIQUIDAÇÃO', 'ducha-higienica-plastica-liquidacao', 'Ducha higiênica plástica em liquidação', 'Ducha higiênica em plástico resistente. Acionamento simples. Produto em liquidação por troca de estoque.', 49.90, 24.90, 'LIQ-017', 30, 0.4, 12, 6, 10, true, true, '[{"url":"https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800","principal":true}]', '{"Material": "Plástico ABS", "Cor": "Branco/Cromado", "Motivo": "Liquidação", "Desconto": "50% OFF"}', '{"liquidacao","desconto","oferta"}');
